general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Przyciemnienie po 4 minutach
listener {
    timeout = 240
    on-timeout = brightnessctl -s set 10%
    on-resume = brightnessctl -r
}

# Wyłącz podświetlenie klawiatury (jeśli jest)
listener {
    timeout = 240
    on-timeout = brightnessctl -sd "*::kbd_backlight" set 0
    on-resume = brightnessctl -rd "*::kbd_backlight"
}

# Lock po 5 min
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# DPMS off po 5.5 min
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Suspend po 30 min na baterii
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
