font=JetBrains Mono:size=8
dpi-aware=yes
pad=8x8

[mouse]
hide-when-typing=yes

[scrollback]
lines=10000

[colors-dark]
alpha=0.92
foreground=e4e4f4
background=0d0e1a

# Czerń / ciemne
regular0=1a1b2e
regular1=ff4d9e
regular2=7dffaf
regular3=ffd06b
regular4=88c5e6
regular5=b4a7e8
regular6=8de8ff
regular7=a8a9c8

# Bright / jasne
bright0=2d2e4d
bright1=ff79b8
bright2=9dffc4
bright3=ffe08c
bright4=a8d6f0
bright5=cdc1ff
bright6=b0f0ff
bright7=e4e4f4

selection-foreground=0d0e1a
selection-background=ff4d9e
urls=88c5e6

[cursor]
#color=0d0e1a ff4d9e
beam-thickness=1.5
